lib/move_nft_free_minter_web/router.ex
defmodule MoveNFTFreeMinterWeb.Router do
  use MoveNFTFreeMinterWeb, :router

  import MoveNFTFreeMinterWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MoveNFTFreeMinterWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MoveNFTFreeMinterWeb do
    pipe_through ~w(browser)a

    post "/auth", SessionController, :create

    # auth
    live "/session/new", WalletLive, :index
  end

  scope "/", MoveNFTFreeMinterWeb do
    pipe_through ~w(browser require_authenticated_user)a

    post "/logout", SessionController, :delete

    # orders
    live "/", MintLive, :index

    # mint page
    live "/mint", MintLive, :index

    # profile page
    live "/profile", ProfileLive, :index
    live "/profile/list_token/:id", ProfileLive, :list_token

    live "/about", AboutLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", MoveNFTFreeMinterWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: MoveNFTFreeMinterWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/move_nft_free_minter_web/views/layout_view.ex
defmodule MoveNFTFreeMinterWeb.LayoutView do
  use MoveNFTFreeMinterWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/move_nft_free_minter_web/templates/layout/_footer.html.heex
<footer class="p-4 bg-white rounded-lg shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800">
	<span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2022 MoveDID</span>
	<ul class="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0">
		<li>
			<a href="https://github.com/NonceGeek/MoveDID" class="mr-4 hover:underline md:mr-6 ">Github</a>
		</li>
	</ul>
</footer>

lib/move_nft_free_minter_web/templates/layout/_header.html.heex
<nav class="bg-white border-gray-200 px-2 sm:px-10 py-2.5 rounded dark:bg-gray-800 ">
  <div class="flex flex-wrap justify-between items-center mx-auto">
    <div class="flex">
      <a href="/" class="flex items-center">
        <span class="self-center text-xl font-semibold whitespace-nowrap text-blue-600 dark:text-white">AwesomeFreeTools@MoveDID</span>
      </a>

      <div class="flex mx-10 space-x-2">
        <%= link "Mint NFT(Gas Only!)", to: Routes.mint_path(@conn, :index), class: "text-blue-600 font-bold hover:bg-gray-100 rounded-lg p-2 dark:text-white" %>
      </div>
      <div class="flex mx-10 space-x-2">
        <%= link "About Us", to: Routes.about_path(@conn, :index), class: "text-blue-600 font-bold hover:bg-gray-100 rounded-lg p-2 dark:text-white" %>
      </div>
    </div>

    <div class="flex items-center space-x-2">
      <%= if @current_user do %>
        <button type="button" class="flex justify-between bg-gray-100 px-2 items-center mr-3 text-sm rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" type="button" data-dropdown-toggle="dropdown">
          <span class="sr-only">Open user menu</span>
          <img class="w-8 h-8 rounded-full" src={@current_user.avatar_url} alt={@current_user.nickname}>
          <span class="pl-2"><%= display_address(@current_user.address) %></span>
        </button>

        <!-- Dropdown menu -->
        <div
          class="hidden z-50 my-4 text-base list-none bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600"
          id="dropdown">
          <div class="py-3 px-4">
            <span class="block text-sm text-gray-900 dark:text-white"><%= @current_user.nickname %></span>
            <span class="block text-sm font-medium text-gray-500 truncate dark:text-gray-400"><%= display_address(@current_user.address) %></span>
          </div>
          <ul class="py-1" aria-labelledby="dropdown">
            <li> <%= link "Profile", class: "block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white", to: Routes.profile_path(@conn, :index) %> </li>
            <li> <%= link "Sign out", class: "block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white", to: Routes.session_path(@conn, :delete), method: :post %> </li>
          </ul>
        </div>
      <% else %>
      <button
        class="text-white bg-blue-600 font-bold hover:bg-blue-700 rounded-lg p-2 dark:text-white"
        phx-click={show_wallet_modal()}
      >
        + Connect Wallet
      </button>
        <.modal id="wallet-modal">
          <%= live_render(@conn, MoveNFTFreeMinterWeb.WalletButtonLive, id: "connect", session: %{"id" => "wallet-connect", "text" => "Log in with Petra Wallet"}) %>
        </.modal>
      <% end %>
    </div>
  </div>
</nav>

<%# <script>
  var themeToggleDarkIcon = document.getElementById('theme-toggle-dark-icon');
  var themeToggleLightIcon = document.getElementById('theme-toggle-light-icon');

  // Change the icons inside the button based on previous settings
  if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia(
      '(prefers-color-scheme: dark)').matches)) {
    themeToggleLightIcon.classList.remove('hidden');
  } else {
    themeToggleDarkIcon.classList.remove('hidden');
  }

  var themeToggleBtn = document.getElementById('theme-toggle');

  themeToggleBtn.addEventListener('click', function () {

    // toggle icons inside button
    themeToggleDarkIcon.classList.toggle('hidden');
    themeToggleLightIcon.classList.toggle('hidden');

    // if set via local storage previously
    if (localStorage.getItem('color-theme')) {
      if (localStorage.getItem('color-theme') === 'light') {
        document.documentElement.classList.add('dark');
        localStorage.setItem('color-theme', 'dark');
      } else {
        document.documentElement.classList.remove('dark');
        localStorage.setItem('color-theme', 'light');
      }

      // if NOT set via local storage previously
    } else {
      if (document.documentElement.classList.contains('dark')) {
        document.documentElement.classList.remove('dark');
        localStorage.setItem('color-theme', 'light');
      } else {
        document.documentElement.classList.add('dark');
        localStorage.setItem('color-theme', 'dark');
      }
    }
  });
</script> %>

<%# <script>
  // On page load or when changing themes, best to add inline in `head` to avoid FOUC
  if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
    document.documentElement.classList.add('dark');
  } else {
    document.documentElement.classList.remove('dark')
  }
</script> %>

lib/move_nft_free_minter_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/move_nft_free_minter_web/templates/layout/live.html.heex
<main class="my-5 space-x-4 max-w-[80rem] mx-auto">
  <%= if live_flash(@flash, :info) do %>
  <div id="alert-1" class="flex p-4 mb-4 bg-blue-100 rounded-lg dark:bg-blue-200" role="alert">
    <svg aria-hidden="true" class="flex-shrink-0 w-5 h-5 text-blue-700 dark:text-blue-800" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
    <span class="sr-only">Info</span>
    <div class="ml-3 text-sm font-medium text-blue-700 dark:text-blue-800">
      <%= live_flash(@flash, :info) %>
    </div>
    <button phx-click="lv:clear-flash" phx-click="lv:clear-flash" type="button" class="ml-auto -mx-1.5 -my-1.5 bg-blue-100 text-blue-500 rounded-lg focus:ring-2 focus:ring-blue-400 p-1.5 hover:bg-blue-200 inline-flex h-8 w-8 dark:bg-blue-200 dark:text-blue-600 dark:hover:bg-blue-300" data-dismiss-target="#alert-1" aria-label="Close">
      <span class="sr-only">Close</span>
      <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
    </button>
  </div>
  <% end %>

  <%= if live_flash(@flash, :error) do %>
  <div id="alert-2" class="flex p-4 mb-4 bg-red-100 rounded-lg dark:bg-red-200" role="alert">
    <svg aria-hidden="true" class="flex-shrink-0 w-5 h-5 text-red-700 dark:text-red-800" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
    <span class="sr-only">Info</span>
    <div class="ml-3 text-sm font-medium text-red-700 dark:text-red-800">
      <%= live_flash(@flash, :error) %>
    </div>
    <button phx-click="lv:clear-flash" phx-value-key="error" type="button" class="ml-auto -mx-1.5 -my-1.5 bg-red-100 text-red-500 rounded-lg focus:ring-2 focus:ring-red-400 p-1.5 hover:bg-red-200 inline-flex h-8 w-8 dark:bg-red-200 dark:text-red-600 dark:hover:bg-red-300" data-dismiss-target="#alert-2" aria-label="Close">
      <span class="sr-only">Close</span>
      <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
    </button>
  </div>
  <% end %>

  <%= @inner_content %>
</main>

lib/move_nft_free_minter_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "MoveDID", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body class="bg-gray-100 font-sen flex flex-col h-screen justify-between">
    <header>
      <%= render "_header.html", assigns %>
    </header>
    <div class="container mb-auto min-w-full">
      <%= @inner_content %>
    </div>

    <%= render "_footer.html", assigns %>
  </body>
</html>